/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "secondary": "#4648d4",
        "surface-tint": "#004dea",
        "outline-variant": "#c3c5d9",
        "on-primary-fixed-variant": "#0039b3",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed-dim": "#b6c4ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#d2d9f4",
        "background": "#faf8ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed": "#001551",
        "error-container": "#ffdad6",
        "outline": "#737688",
        "on-secondary": "#ffffff",
        "tertiary-container": "#007751",
        "primary-container": "#0055ff",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#b6c4ff",
        "surface-container": "#eaedff",
        "secondary-container": "#6063ee",
        "on-surface-variant": "#434656",
        "surface-variant": "#dae2fd",
        "on-tertiary-container": "#83ffc6",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "on-primary-container": "#e3e6ff",
        "on-surface": "#131b2e",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#07006c",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#e1e0ff",
        "inverse-surface": "#283044",
        "tertiary": "#005c3e",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-background": "#131b2e",
        "primary": "#0041c8",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "md": "16px",
        "margin-edge": "32px",
        "lg": "24px",
        "gutter": "24px",
        "2xl": "48px",
        "3xl": "64px",
        "xl": "32px",
        "base": "4px",
        "xs": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["Geist", "monospace"],
      }
    },
  },
  plugins: [],
}
